export const CERTIFICATE_LIST_REQUEST = 'CERTIFICATE_LIST_REQUEST';
export const CERTIFICATE_LIST_SUCCESS = 'CERTIFICATE_LIST_SUCCESS';
export const CERTIFICATE_LIST_FAIL = 'CERTIFICATE_LIST_FAIL';

export const CERTIFICATE_DETAIL_REQUEST = 'CERTIFICATE_DETAIL_REQUEST';
export const CERTIFICATE_DETAIL_SUCCESS = 'CERTIFICATE_DETAIL_SUCCESS';
export const CERTIFICATE_DETAIL_FAIL = 'CERTIFICATE_DETAIL_FAIL';

export const CERTIFICATE_CREATE_REQUEST = 'CERTIFICATE_CREATE_REQUEST';
export const CERTIFICATE_CREATE_SUCCESS = 'CERTIFICATE_CREATE_SUCCESS';
export const CERTIFICATE_CREATE_FAIL = 'CERTIFICATE_CREATE_FAIL';
export const CERTIFICATE_CREATE_RESET = 'CERTIFICATE_CREATE_RESET';

export const CERTIFICATE_UPDATE_REQUEST = 'CERTIFICATE_UPDATE_REQUEST';
export const CERTIFICATE_UPDATE_SUCCESS = 'CERTIFICATE_UPDATE_SUCCESS';
export const CERTIFICATE_UPDATE_FAIL = 'CERTIFICATE_UPDATE_FAIL';
export const CERTIFICATE_UPDATE_RESET = 'CERTIFICATE_UPDATE_RESET';

export const CERTIFICATE_DELETE_REQUEST = 'CERTIFICATE_DELETE_REQUEST';
export const CERTIFICATE_DELETE_SUCCESS = 'CERTIFICATE_DELETE_SUCCESS';
export const CERTIFICATE_DELETE_FAIL = 'CERTIFICATE_DELETE_FAIL';
