export const CONTACT_MAKE_REQUEST = 'CONTACT_MAKE_REQUEST';
export const CONTACT_MAKE_SUCCESS = 'CONTACT_MAKE_SUCCESS';
export const CONTACT_MAKE_FAIL = 'CONTACT_MAKE_FAIL';
export const CONTACT_MAKE_RESET = 'CONTACT_MAKE_RESET';

export const CONTACT_ARCHIVE_REQUEST = 'CONTACT_ARCHIVE_REQUEST';
export const CONTACT_ARCHIVE_SUCCESS = 'CONTACT_ARCHIVE_SUCCESS';
export const CONTACT_ARCHIVE_FAIL = 'CONTACT_ARCHIVE_FAIL';
export const CONTACT_ARCHIVE_RESET = 'CONTACT_ARCHIVE_RESET';

export const CONTACT_LIST_REQUEST = 'CONTACT_LIST_REQUEST';
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS';
export const CONTACT_LIST_FAIL = 'CONTACT_LIST_FAIL';

export const CONTACT_DELETE_REQUEST = 'CONTACT_DELETE_REQUEST';
export const CONTACT_DELETE_SUCCESS = 'CONTACT_DELETE_SUCCESS';
export const CONTACT_DELETE_FAIL = 'CONTACT_DELETE_FAIL';
export const CONTACT_DELETE_RESET = 'CONTACT_DELETE_RESET';
