export const CONTACT_MAKE_REQUEST = 'CONTACT_MAKE_REQUEST';
export const CONTACT_MAKE_SUCCESS = 'CONTACT_MAKE_SUCCESS';
export const CONTACT_MAKE_FAIL = 'CONTACT_MAKE_FAIL';
export const CONTACT_MAKE_RESET = 'CONTACT_MAKE_RESET';

export const CONTACT_ARCHIVE_REQUEST = 'CONTACT_ARCHIVE_REQUEST';
export const CONTACT_ARCHIVE_SUCCESS = 'CONTACT_ARCHIVE_SUCCESS';
export const CONTACT_ARCHIVE_FAIL = 'CONTACT_ARCHIVE_FAIL';
export const CONTACT_ARCHIVE_RESET = 'CONTACT_ARCHIVE_RESET';
