export const PORTFOLIO_LIST_REQUEST = 'PORTFOLIO_LIST_REQUEST';
export const PORTFOLIO_LIST_SUCCESS = 'PORTFOLIO_LIST_SUCCESS';
export const PORTFOLIO_LIST_FAIL = 'PORTFOLIO_LIST_FAIL';

export const PORTFOLIO_DETAIL_REQUEST = 'PORTFOLIO_DETAIL_REQUEST';
export const PORTFOLIO_DETAIL_SUCCESS = 'PORTFOLIO_DETAIL_SUCCESS';
export const PORTFOLIO_DETAIL_FAIL = 'PORTFOLIO_DETAIL_FAIL';
