export const SKILL_LIST_REQUEST = 'SKILL_LIST_REQUEST';
export const SKILL_LIST_SUCCESS = 'SKILL_LIST_SUCCESS';
export const SKILL_LIST_FAIL = 'SKILL_LIST_FAIL';

export const SKILL_DETAIL_REQUEST = 'SKILL_DETAIL_REQUEST';
export const SKILL_DETAIL_SUCCESS = 'SKILL_DETAIL_SUCCESS';
export const SKILL_DETAIL_FAIL = 'SKILL_DETAIL_FAIL';

export const SKILL_CREATE_REQUEST = 'SKILL_CREATE_REQUEST';
export const SKILL_CREATE_SUCCESS = 'SKILL_CREATE_SUCCESS';
export const SKILL_CREATE_FAIL = 'SKILL_CREATE_FAIL';
export const SKILL_CREATE_RESET = 'SKILL_CREATE_RESET';

export const SKILL_UPDATE_REQUEST = 'SKILL_UPDATE_REQUEST';
export const SKILL_UPDATE_SUCCESS = 'SKILL_UPDATE_SUCCESS';
export const SKILL_UPDATE_FAIL = 'SKILL_UPDATE_FAIL';
export const SKILL_UPDATE_RESET = 'SKILL_UPDATE_RESET';

export const SKILL_DELETE_REQUEST = 'SKILL_DELETE_REQUEST';
export const SKILL_DELETE_SUCCESS = 'SKILL_DELETE_SUCCESS';
export const SKILL_DELETE_FAIL = 'SKILL_DELETE_FAIL';
